SELECT EMPNO AS EMPLOYEE_NO,
 ENAME AS EMPLOYEE_NAME,
 JOB,
 MGR AS MANAGER,
 HIREDATE,
 SAL AS SALARY,
 COMM AS COMMISSION,
 DEPTNO AS DEPARTMENT_N0
 FROM EMP
ORDER BY DEPTNO DESC, ENAME ASC; /*º°Äª*/