/* DECODE문으로 GROUPING함수를 적용해 결과 표기 */
/* DECODE(A, B, X, Y) > A=B이면 X 출력, A와 B가 다르면 Y 출력 */
SELECT DECODE(GROUPING(DEPTNO), 1, 'ALL_DEPT', DEPTNO) AS DEPTNO,
        DECODE(GROUPING(JOB), 1, 'ALL_JOB', JOB) AS JOB,
        COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL)
 FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY DEPTNO, JOB;